### ISSUE TITLE
innerData is undefined when doing a search

### ISSUE THREAD

**Issue by patrickjquinn** [PaquitoSoft/goear-api#2]
Howdy, currently getting "node_modules/goear_api/lib/goear_api.js:90 totalCount = innerData.totalCount;" when doing a standard search query, any hopes you can update the API to fix this or does this require a little bit of hacking on my end ;) 

Seems that the request to the search URL is currently returning a 404 even though its successfully getting the body and when you remove the responseStatus check it works just fine.

**Comment by PaquitoSoft** [comment]
@patrickjquinn I will take a look as soon as I have the time to check it.

**Comment by PaquitoSoft** [comment]
@patrickjquinn Seems goear changed the way they handle queries that return no results. 
I've just published a new version of the module in NPM with the corresponding fix.

**Comment by patrickjquinn** [comment]
Wow that was super quick! Thanks for this :) will add a bit of failover to my service to ensure i can handle stuff like this in future ! :+1:
